# install.packages("dplyr")
# install.packages("readr")
# install.packages("data.table")
# install.packages("stringr")
# install.packages("data.tree")
# install.packages("purrr")
# install.packages("DiagrammeR")
# install.packages("ggformula")
# install.packages("permutations")
# install.packages("Hmisc")
# install.packages("tidyverse")
# install.packages("gdata")
# install.packages("vctrs")
# install.packages('index0')
# install.packages('gghighlight')
# install.packages("stringi")
# install.packages("igraph")
# install.packages("modeest")
# install.packages("permutations")

require(stringi)
require(gghighlight)
require(index0)
require(vctrs)
require(tidyverse)
require(ggformula)
require(dplyr)
require(data.table)
require(stringr)
require(readr)
require(purrr)
require(data.tree)
require(permutations)
require(pracma)
require(Hmisc)
require(igraph)
require(modeest)
require(magrittr)
require(tidyr)

options(digits=22)



